name: AI PR Review via /review Comment

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  ai_review:
    if: github.event.issue.pull_request != null && (
         contains(github.event.comment.body, '/review') ||
         contains(github.event.comment.body, '/optimize') ||
         contains(github.event.comment.body, '/security') ||
         contains(github.event.comment.body, '/test')
       )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install openai requests PyGithub

      - name: Print GitHub event JSON (for debug)
        run: cat "$GITHUB_EVENT_PATH"

      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python .github/scripts/ai_review.py
