name: DeepSeek Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deepseek-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python & dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install requirements
        run: |
          pip install requests PyGithub python-dotenv
          sudo apt-get install -y gh

      - name: Get PR diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > pr.diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DeepSeek Review
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python3 .github/scripts/deepseek_review.py
