name: AI Code Review

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Shippie
        run: bun add shippie@latest

      - name: Run Shippie AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          bunx shippie review \
            --github \
            --openai \
            --base ${{ github.event.pull_request.base.sha }} \
            --head ${{ github.event.pull_request.head.sha }} \
            --telemetry false
