name: AI Code Review

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required so Shippie can access full commit history

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Shippie CLI
        run: bun add shippie@latest

      - name: Run AI Code Review with Shippie
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          bunx shippie --github --openai
